# 02807: Project 2
 
## Practical information
 
* This project must be completed in groups of 3 students.
    * The group must be registered on the course site on DTU Learn: My Course > Groups
    * Groups must be registered anew (even if you already registered for Project 1)
* This project must be handed in as a jupyter notebook to the course site on DTU Learn. 
    * Go to the Course Content > Assignments tab to upload your submission. 
* This project is due on Monday, November 29, 20:00.

## Submission rules

* Each group has to hand in *one* notebook (`.ipynb`) with their solutions, including a filled out Contribution table (see below).
* Your solution must be written in Python.
* For each question you should use the cells provided ("`# your code goes here`" and "*your explanation here*") for your solution
    * It is allowed to add code cells within a question block, but consider if it's really necessary.
* You should not remove the problem statements, and you should not modify the structure of the notebook.
* Your notebook should be runnable and readable from top to bottom.
    * Meaning that your code cells work when run in order (from top to bottom).
    * Output of any cell depends only on itself and cells above it.
* Your notebook should be submitted after having been run from top to bottom.
    * This means outputs are interpretable without necessarily running your cells.
    * The simplest way to achieve this is using the jupyter menu item Kernel > Restart & Run All just prior to submission. If any cell fails when you do this, your notebook is not ready for submission.
    * Exercise 3 in particular will take time to finish, plan accordingly, that is, make sure you have time to run your notebook from top to bottom.
* Failure to comply may make it impossible for us to evaluate your submission properly, which will likely negatively impact the points awarded.

## Solution guidelines
* Data processing is via Spark for the first three exercises and pandas/SQL in the fourth exercise.
* Where naming of dataframes and functions are explicitly stated, these must be used.
* Your solutions will be evaluated by correctness, code quality and interpretability of the output. 
    * You have to write clean, readable and efficient Spark code that will generate sensible execution plans.
    * You have to write clean, readable and efficient SQL queries.
    * Your tables and visualisations should be meaningful and easy to read. This requires, but is not limited to, including headers, legends and well-written (brief) descriptions for graphs/charts. In this step you've found the data processing solution, so put also some effort into its presentation.

## Colaboration policy
 
* It is not allowed to collaborate on the exercises with students outside your group, except for discussing the text of the exercise with teachers and fellow students enrolled on the course in the same semester. 
* It is not allowed to exchange, hand-over or in any other way communicate solutions or parts of solutions to the exercises. 
* It is not allowed to use solutions from similar courses, or solutions found elsewhere.

## Contribution table and grading

* The total amount of points in the project is 150.
* You have to indicate who has solved each part of each exercise in a **contribution table**. 
* A group member can take credit for solving a part of an exercise only if they have contributed **substantially** to the solution. 
    * Simple contributions, such as correcting a small bug or double-checking the results of functions, are not sufficient for taking credit for a solution.
    * Several group members can take credit for the same solution if they all have contributed substantially to it.
* Each group member must contribute **at least 65 points**. 
    * If no name is provided for an exercise's part, **all group members** are considered contributors to it.
* Group members should decide amongst themselves how to collaborate on the project to meet these constraints.  
* Scores are individual. The score $\text{score}(m)$ for a group member $m$ ranges from 0 to 10 and is calculated as follows: 

  * $\text{individual-score}(m) = \frac{\text{total number of points for the parts correctly solved by }m}{\text{total number of points for the parts contributed by }m}$

  * $\text{group-score} = \frac{\text{total number of points correctly solved by any group member}}{\text{total number of points in the project}}$

  * $\text{score}(m) =  7.5 \cdot \text{individual-score}(m) + 2.5 \cdot \text{group-score}$
  
  
* The following is an example of a contributions table:

|        | Exercise 1 | Exercise 2 | Exercise 3 | Exercise 4 |
|--------|------------|------------|------------|------------|
| **Part 1** | John       |    Mary        |     Ann       |   Mary, Ann         |
| **Part 2** |     Mary       |    Mary        |   Ann         |    John, Ann        |
| **Part 3** |     John, Mary, Ann       |      John, Ann      |   John         | John      |
| **Part 4** | Ann       |  Ann          |     John, Mary       | John       |
| **Part 5** | **n.a.**     | John, Mary, Ann           | **n.a.**       | **n.a.**       |


* **Example**: in the contribution table above, suppose that all parts are solved correctly except for those of Exercise 4 which are all wrong. Then Ann's score is calculated as follows:

  * $\text{individual-score}(Ann) = \frac{5+5+10+5+5+15+15}{5+5+10+5+5+15+15+15+5} = \frac{60}{80} = 0.75$

  * $\text{group-score} = \frac{95}{150} = 0.633$

  * $\text{score}(Ann) = 7.5\cdot 0.75 + 2.5 \cdot 0.633 = 7.21$


# Group contribution table 

This table must be filled before submission.



In [1]:
import pandas as pd

d = {'Exercise 1' : ['', '', '', '', 'n.a'], 
     'Exercise 2' : ['', '', '', '', ''],
     'Exercise 3' : ['', '', '', '', 'n.a'],
     'Exercise 4' : ['', '', '', '', 'n.a'],
     } 
  
ct = pd.DataFrame(d, index=['Part 1', 'Part 2', 'Part 3', 'Part 4', 'Part 5']) 

ct

Exercise 1 Exercise 2 Exercise 3 Exercise 4
Part 1                                            
Part 2                                            
Part 3                                            
Part 4                                            
Part 5        n.a                   n.a        n.a

# The AirBnB dataset

<img src="https://www.esquireme.com/public/images/2019/11/03/airbnb-678x381.jpg" alt="airbnb" width="400"/>

[Airbnb](http://airbnb.com) is an online marketplace for arranging or offering lodgings. In the first three exercises you will use Spark to analyze data obtained from the Airbnb website (stricly speaking via data scraped by [insideairbnb](http://insideairbnb.com/get-the-data.html)). The purpose of your analysis is to extract insights about listings as a whole, specifics about London, and sentiment analysis of reviews (word positivity).


## Loading data
The dataset consists of listings (offered lodgings) and reviews (submitted by users). The `.csv`'s you'll work with vary between the first three exercises, but is structured so that the function below will load it into a spark dataframe.

In [2]:
def load_csv_as_dataframe(path):
    return spark.read.option('header', True) \
                .option('inferSchema', True) \
                .option('multiLine', 'True') \
                .option('escape', '"') \
                .option('mode', 'DROPMALFORMED')\
                .csv(path)

## Imports and Spark session

* You'll need to adapt the `JAVA_HOME` environment variable to your setup. 
* You should set the `spark.driver.memory` value to the amount of memory on your machine. 
* It may be required for you to install some of the packages imported below (e.g. pandasql).

In [3]:
# Instructions on p. 20 Learning Spark, 2nd ed.
# Here's a quick-guide, googling may also be required
# 1) Install pyspark via conda/pip
#          pyspark requires the JAVA_HOME environment variable is set.
# 2) Install JDK 8 or 11, figure out the install location
#          Suggest to use https://adoptopenjdk.net/
# 3) Update the JAVA_HOME environment variable set programmatically below 
#    with your install location specifics

# JAVA_HOME environment variable is set programatically below
# but you must point it to your local install

import os
os.environ['JAVA_HOME'] = "C:\Program Files\Java\jdk8u312-b07"

# If you get "Job aborted due to stage failure" and 
# "Python worker failed to connect back." exceptions, 
# this should be solved by additionally setting these 
# environment variables

os.environ['PYSPARK_PYTHON'] = 'python'
os.environ['PYSPARK_DRIVER_PYTHON'] = 'jupyter'
os.environ['PYSPARK_DRIVER_PYTHON_OPTS'] = 'notebook'

In [ ]:
# !pip3 install PyQt5==5.9.2
# !pip3 install --user PyQt5==5.15.6

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
%matplotlib qt5

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark import SparkContext, SparkConf
from pyspark.sql.functions import udf
import re
from pyspark.sql.functions import length
from pyspark.sql.functions import col

from pyspark.sql.types import StringType

from pandas_profiling import ProfileReport

# import pandasql as psql

In [5]:
# Sets memory limit on driver and to use all CPU cores
conf = SparkConf().set('spark.ui.port', '4050') \
        .set('spark.driver.memory', '4g') \
        .setMaster('local[*]')

sc = pyspark.SparkContext(conf=conf)
spark = SparkSession.builder.getOrCreate()

In [6]:
spark

In [7]:
sc.getConf().getAll()

[('spark.driver.host', 'PC-5CG1047FFW.danfoss.net'),
 ('spark.driver.memory', '4g'),
 ('spark.driver.port', '52386'),
 ('spark.app.startTime', '1637505034712'),
 ('spark.sql.warehouse.dir',
  'file:/C:/Users/U388314/Documents/02807%20-%20Computational%20Tools/spark-warehouse'),
 ('spark.executor.id', 'driver'),
 ('spark.app.name', 'pyspark-shell'),
 ('spark.ui.port', '4050'),
 ('spark.rdd.compress', 'True'),
 ('spark.serializer.objectStreamReset', '100'),
 ('spark.master', 'local[*]'),
 ('spark.submit.pyFiles', ''),
 ('spark.submit.deployMode', 'client'),
 ('spark.ui.showConsoleProgress', 'true'),
 ('spark.app.id', 'local-1637505036267')]

# Exercise 1: Listings and cities (20 pts)

In this exercise you must use Spark to do the data processing. 
* For parts where you present tabular data, this entails calling `toPandas` as the final step of your query. 
* For parts requiring visualisation, the `toPandas` call should be followed only by functions necessary to customize the plotting/layout steps (i.e. no data processing take place after your spark dataframe is materialized).


## Part 1: Preparing the dataframe (5 pts)

Your data source is [this zip archive](https://data-download.compute.dtu.dk/c02807/listings.csv.zip) which you must uncompress and place in the same folder as this notebook. It is loaded in the next cell and named `df_listings`.

After the data is read, you should select the columns necessary for exercise 1, 2 and 3 (by reading ahead or iteratively extend this loading code). Name this dataframe `df_listings_analysis` and make use of caching.

Prices are in local currency, but are nonetheless prefixed with `$` and contains thousands separator commas. You will need to remove these characters and cast the price column to `pyspark.sql.types.DoubleType`. Observe that if this casting is not possible, the result of the cast is `null`.

In [8]:
df_listings = load_csv_as_dataframe('listings.csv')

In [9]:
spark.read.option('header',True).option('inferSchema',True).csv('listings.csv').printSchema()

root
 |-- id: string (nullable = true)
 |-- listing_url: string (nullable = true)
 |-- scrape_id: string (nullable = true)
 |-- last_scraped: string (nullable = true)
 |-- name: string (nullable = true)
 |-- summary: string (nullable = true)
 |-- space: string (nullable = true)
 |-- description: string (nullable = true)
 |-- experiences_offered: string (nullable = true)
 |-- neighborhood_overview: string (nullable = true)
 |-- notes: string (nullable = true)
 |-- transit: string (nullable = true)
 |-- access: string (nullable = true)
 |-- interaction: string (nullable = true)
 |-- house_rules: string (nullable = true)
 |-- thumbnail_url: string (nullable = true)
 |-- medium_url: string (nullable = true)
 |-- picture_url: string (nullable = true)
 |-- xl_picture_url: string (nullable = true)
 |-- host_id: string (nullable = true)
 |-- host_url: string (nullable = true)
 |-- host_name: string (nullable = true)
 |-- host_since: string (nullable = true)
 |-- host_location: string (nullable

In [10]:
# Your code goes here
df_listings_analysis = df_listings.select(F.col('id'),F.col('listing_url'),F.col('neighbourhood_cleansed'),
                                            F.col('city'),F.col('price'),F.col('review_scores_rating'), 
                                            F.col('number_of_reviews'),F.col('property_type')) \
                                  .withColumn("price", F.translate(F.col("price"), "[$,]","") \
                                  .cast(pyspark.sql.types.DoubleType())) \
                                  .cache()

df_listings_analysis.toPandas()

id                            listing_url  \
0          145320    https://www.airbnb.com/rooms/145320   
1          155220    https://www.airbnb.com/rooms/155220   
2          155685    https://www.airbnb.com/rooms/155685   
3          164448    https://www.airbnb.com/rooms/164448   
4          170651    https://www.airbnb.com/rooms/170651   
...           ...                                    ...   
1330739  38882480  https://www.airbnb.com/rooms/38882480   
1330740  38883126  https://www.airbnb.com/rooms/38883126   
1330741  38885064  https://www.airbnb.com/rooms/38885064   
1330742  38887396  https://www.airbnb.com/rooms/38887396   
1330743  38891798  https://www.airbnb.com/rooms/38891798   

                          neighbourhood_cleansed       city   price  \
0                                     Södermalms  Stockholm  1272.0   
1                                     Skarpnäcks  Stockholm  1203.0   
2                                     Södermalms  Stockholm  3209.0   
3                                     Södermalms  Stockholm   597.0   
4                                     Södermalms  Stockholm   734.0   
...                                          ...        ...     ...   
1330739                    Meadows and Southside  Edinburgh    99.0   
1330740     Canongate, Southside and Dumbiedykes  Edinburgh    99.0   
1330741                            New Town West  Edinburgh    99.0   
1330742  Craigleith, Orchard Brae and Crewe Toll  Edinburgh   150.0   
1330743                    Meadows and Southside  Edinburgh   131.0   

        review_scores_rating number_of_reviews property_type  
0                         97                72     Apartment  
1                       None                 0         House  
2                         94                22     Apartment  
3                         97               311     Apartment  
4                         93                33     Apartment  
...                      ...               ...           ...  
1330739                 None                 0         House  
1330740                 None                 0         House  
1330741                 None                 0         House  
1330742                 None                 0     Apartment  
1330743                 None                 0     Apartment  

[1330744 rows x 8 columns]

## Part 2: Listing and neighbourhood counts (5 pts)

Compute and visualise the number of listings and the number of different neighbourhoods per city, restricted to the 15 cities having the most listings. The x-axis should be ordered by number of listings (high to low).

Make sure to use the `neighbourhood_cleansed` column in your computations.


In [ ]:
# your code goes here
%matplotlib inline

listings = df_listings_analysis.groupBy('city') \
                               .agg(F.countDistinct('neighbourhood_cleansed').alias('neighbourhood'),
                                    F.count('listing_url').alias('No_listing_url')) \
                               .sort(F.desc(F.count('listing_url'))) \
                               .limit(15).toPandas() \
                               .set_index('city')

#plot the counts
_ = listings.plot( kind= 'bar' , secondary_y= 'neighbourhood' , rot= 0 ,figsize=(16,10))
_.set_xlabel("City")
_.set_ylabel("Number of listings")
plt.title('Listing and Neighbourhood counts',fontsize=18)
plt.show()

## Part 3: Price averages (5 pts)

Compute and visualise the average price of listings per city, restricted to the 15 cities having the most listings.

In [ ]:
# your code goes here
%matplotlib inline

avg_listings = df_listings_analysis.groupBy('city') \
                               .agg(F.avg('price').alias('Price')) \
                               .sort(F.desc(F.count('listing_url'))) \
                               .limit(15).toPandas() 

#i havent sorted the values because he says that should be ordered by the number of listings
_ = avg_listings.set_index('city').plot( kind= 'bar'  , rot= 0 ,figsize=(18,10)) #sort_values(by='avg(price)',ascending=False)
_.set_xlabel("City")
_.set_ylabel("Average price")
plt.title('Prices average',fontsize=18)
plt.show()

## Part 4: Value for money (5 pts)

The value of a listing is its rating divided by its price. The value of a city is the average value of its listings. 

Prices are only comparable when the local currency is the same. We'll therefore consider a subset of Euro-zone cities as defined in `eurozone_cities`.

Compute and visualise the value per city, restricted to the Euro-zone cities.

In [ ]:
eurozone_cities = [
    'Paris', 'Roma', 'Berlin', 'Madrid', 'Amsterdam', 'Barcelona', 'Milano', 'Lisboa',
    'München', 'Wien', 'Lyon', 'Firenze', 'Porto', 'Napoli', 'Bordeaux', 'Venezia',
    'Málaga', 'Sevilla', 'València'
]

In [ ]:
# your code goes here
%matplotlib inline

listings_value =F.col('review_scores_rating')/F.col('price')
eu_value = df_listings_analysis.filter(F.col('city').isin(eurozone_cities)) \
                                        .withColumn('listings_value',listings_value) \
                                        .groupBy('city').agg(F.avg('listings_value').alias('Value')) \
                                        .toPandas()

_ = eu_value.set_index('city').sort_values(by='Value',ascending=False).plot( kind= 'bar'  , rot= 0 ,figsize=(18,10)) #sort_values(by='avg(price)',ascending=False)
plt.title('Value for money',fontsize=18)
_.set_xlabel("City")
_.set_ylabel("Value of city")
plt.show()                                  

# Exercise 2: The case of London (30 pts)

In this exercise you must use Spark to do the data processing. 
* For parts where you present tabular data, this entails calling `toPandas` as the final step of your query. 
* For parts requiring visualisation, the `toPandas` call should be followed only by functions necessary to customize the plotting/layout steps (i.e. no data processing take place after your spark dataframe is materialized). 
* You may need multiple queries to solve the individual parts.

Your dataframe is a subset of `df_listings_analysis` and should be named `df_listings_london`.

In [11]:
# your code goes here
df_listings_london = df_listings_analysis.filter(F.col('city')=='London')
#df_listings_london.toPandas()        

## Part 1: Price distribution (5 pts)

Compute and visualise the distribution of prices, for all prices up to and including the 95-percentile. Additionally, compute and visualise the distribution of prices, for all prices above the 95-percentile.

In [ ]:
# your code goes here
%matplotlib inline

quantile_below = F.col('price')<=df_listings_london.approxQuantile('price',[0.95],0)[0]
quantile = F.col('price')>df_listings_london.approxQuantile('price',[0.95],0)[0]

df1 = df_listings_london.filter(quantile_below).toPandas()
df2 = df_listings_london.filter(quantile).toPandas()

fig, ax = plt.subplots(nrows=1,ncols=2,figsize = (16,8))
ax[0].hist(df1['price'], density = False, bins = 20)
ax[1].boxplot(df2['price'])  # Use a box plot to better visualise the listings & prices above 95th percentile
ax[0].set_title('Including 95th Percentile')
ax[1].set_title('Above 95th Percentile')
ax[0].set_xlabel("Price")
ax[0].set_ylabel("Number of listings")
ax[1].set_xlabel("Listings")
ax[1].set_ylabel("Price")
plt.show()

## Part 2: Prices by type of property (5 pts)

Compute and visualise the average price and average rating per type of property, for property types with 75 or more listings. 

Your visualisation should be a single bar chart with two y-axes and two bars per property type. The x-axis should be ordered by average rating.

In [ ]:
# your code goes here
%matplotlib inline

price_property = df_listings_london.groupBy('property_type') \
                                    .agg(F.avg('price').alias('Price'),
                                         F.avg('review_scores_rating').alias('Review Scores'))\
                                    .filter(F.count('listing_url')>75).toPandas()
                                    
_=price_property.set_index('property_type').sort_values(ascending=False,by='Review Scores')\
                        .plot( kind= 'bar' , secondary_y= 'Review Scores' , rot= 0 ,figsize=(20,18))
plt.title('Properties',fontsize=18)
_.set_xlabel("Property type")
_.set_ylabel("Average rating")
plt.show()

## Part 3: Best offering in the neighbourhood (10 pts)

The value of a listing is its rating divided by its price. Compute and display a dataframe (with the columns you selected in Exercise 1 and those computed in this part) with the 3 highest valued listings in each neighbourhood, and having a value above 5. Make sure to use the `neighbourhood_cleansed` column in your computations.

Computing ranks based on value can be achieved using `pyspark.sql.window.Window`. This may produce equal ranks (i.e. when the value of two listings are the same).

Remember to use `pd.set_option('display.max_rows', <n>)` with appropriate `<n>` so all rows are displayed.

In [ ]:
# your code goes here
listings_value=F.col('review_scores_rating')/F.col('price')
value = df_listings_london.filter(F.col('review_scores_rating')!='NaN')\
                             .withColumn('listings_value',listings_value)
                            

windowSpec  = pyspark.sql.window.Window.partitionBy(value["neighbourhood_cleansed"])\
                                                        .orderBy(value["listings_value"].desc())


best_value = value.withColumn("rank",pyspark.sql.functions.dense_rank().over(windowSpec)) \
                             .groupBy('neighbourhood_cleansed','listings_value','rank') \
                             .agg(F.avg(F.col('price'))) \
                             .filter(F.col('listings_value')>5) \
                             .filter(F.col('rank')<=3) \
                             .toPandas()

                                      
pd.set_option('display.max_rows',len(best_value))
best_value

## Part 4: Activity by month (5 pts)

Activity is given by the number of reviews received in a given time period. Compute and visualise the activity based on month, that is, the total number of reviews given in January, February, etc..

Your additional data source is [this zip archive](https://data-download.compute.dtu.dk/c02807/reviews_london.csv.zip) which you must uncompress and place in the same folder as this notebook. It is loaded in the next cell and named `df_reviews_london`.

In [12]:
df_reviews_london = load_csv_as_dataframe('reviews_london.csv')
#df_reviews_london.toPandas()

In [ ]:
# your code goes here
%matplotlib inline

activity = df_reviews_london.withColumn('month',F.date_format('date',"MMMM")) \
                            .groupBy('month').agg(F.count('reviewer_id').alias('No_reviewers')) \
                            .toPandas()

month_order=['January','February','March','April','May','June','July','August','September','October','November','December']
_ = activity.set_index('month').loc[month_order].plot( kind= 'bar', rot= 0 ,figsize=(18,10))
plt.title('Activity by month',fontsize=18)
_.set_xlabel("Month")
_.set_ylabel("Number of reviews")
plt.show()    

## Part 5: Reviews per listing (5 pts)

Each London listing has received 0 or more reviews. 

Display a dataframe showing 1) The number of listings, 2) The average number of reviews a listing receives, 3) The standard deviation of the reviews per listing distribution, 4) The minimum number of reviews any listing has received, and 5) The maximum number of reviews any listing has received.

In [13]:
# your code goes here
df_listings_london=df_listings_london.withColumnRenamed("id","listing_id")
df_listings_reviews=df_listings_london.join(df_reviews_london, on=['listing_id'], how='left')

df_description=df_listings_reviews.select(F.col('listing_id'),F.col('id'))\
                                        .groupBy('listing_id')\
                                        .agg(F.count('id'))\
                                        .describe('count(id)')
df_description.toPandas()

summary           count(id)
0   count               33100
1    mean  25.268640483383685
2  stddev  46.943509453552345
3     min                   0
4     max                 690

# Exercise 3: Word sentiment (45 pts)

In this exercise you must use Spark to do the data processing. For parts where you present tabular data, this entails calling `toPandas` as the final step of your query. You may need multiple queries to solve the individual parts.

The goal here is to determine what sentiment (positive or negative) words in reviews have. Roughly speaking, we want each word to be assigned a score based on the rating of the reviews in which the word occurs in the review comment. We'd expect words such as "clean", "comfortable", "superhost" to receive high scores, while words such as "unpleasant", "dirty", "disgusting" would receive low scores.

As individual reviews do not have a rating, we'll consider the rating of individual reviews to be the rating of its related listing (i.e. assuming each review gave the average rating (`review_scores_rating`) of the listing). 

The score of a word is given by the mean review rating over the reviews in which that word occurs in the comment. We require words to appear in at least 0.5% (1 in 200) listings, and to be at least 4 characters, for it to have a defined score.

Formally, when a word $w$ occurs in at least $0.5\%$ of listings and $|w| > 3$, its score is

$
\begin{align*}
score(w) = \frac{1}{|C_w|}\sum_{comment \in C_w} \text{review_rating}(comment)
\end{align*}
$
, where 
* $C_w = \{comment \mid w \text{ occurs in } \text{clean_text}(comment)\}$, the set (so no duplicates) of comments in which $w$ occurs, and
* $\text{clean_text}(comment)$ is the result of your `clean_text` function defined below, and
* $\text{review_rating}(comment)$ is the `review_scores_rating` of the listing which this $comment$ is related to.


## Part 1: Toy data (15 pts)

To get started we'll consider a toy example where the input is `df_sentiment_listings_toy` and `df_sentiment_reviews_toy` defined in the next code cell. You should provide an implementation of `calculate_word_scores_toy` in the subsequent code cell. Your implementation should result in a query that when given the toy example dataframes as input and is materialized with `toPandas()` produces this table:

|    | word   |   word_score |   listing_occurences |   word_occurences |   comment_occurences |
|---:|:-------|-------------:|---------------------:|------------------:|---------------------:|
|  0 | aaaa   |      7       |                    3 |                 5 |                    5 |
|  1 | bbbb   |      6.66667 |                    2 |                 3 |                    3 |
|  2 | eeee   |      0       |                    1 |                 1 |                    1 |
|  3 | dddd   |      5       |                    1 |                 1 |                    1 |
|  4 | cccc   |      5       |                    2 |                 2 |                    2 |'

Observe that `word_occurences` and `comment_occurences` are the same as words occuring multiple times in a comment are counted once, and that `clean_text` is used to ignore casing and discard non-words. Additionally, any word occuring at least once will occur in more than 1 out of 200 listings on this toy data.

In [ ]:
from pyspark.sql.types import StructType, StructField, StringType

schema_listings = StructType([
    StructField('id', StringType(), True),
    StructField('review_scores_rating', StringType(), True),
])
data_listings = [
    {'id': '0', 'review_scores_rating': '10'},
    {'id': '1', 'review_scores_rating': '5'},
    {'id': '2', 'review_scores_rating': '0'},
]
df_sentiment_listings_toy = spark.createDataFrame(data_listings, schema_listings)

schema_reviews = StructType([
    StructField('listing_id', StringType(), True),
    StructField('id', StringType(), True),
    StructField('comments', StringType(), True),
])
data_reviews = [
    {'listing_id': '0', 'id': '100', 'comments': 'aaaa bbbb          cccc'},
    {'listing_id': '0', 'id': '101', 'comments': 'aaaa bbbb '},
    {'listing_id': '0', 'id': '102', 'comments': 'aaaa aAAa          aaaa'},
    {'listing_id': '1', 'id': '103', 'comments': 'Aaaa bbb ccc'},
    {'listing_id': '1', 'id': '104', 'comments': 'dddd %ˆ&*'},
    {'listing_id': '2', 'id': '105', 'comments': 'AaaA'},
    {'listing_id': '2', 'id': '106', 'comments': 'bbbb ccc e&eˆˆee'},
    {'listing_id': '2', 'id': '107', 'comments': 'cccc cccc'},
]

df_sentiment_reviews_toy = \
    spark.createDataFrame(data_reviews, schema_reviews) \
        .select(F.col('listing_id'), F.col('id').alias('comment_id'), F.col('comments'))

In [14]:
# your code goes here
def clean_text(col):
    """
        Cleans the text (comment) associated with col. The
        cleaning should:
            1) Lower case the text
            2) Turn multiple whitespaces into single whitespaces
            3) Remove anything but letters, digits and whitespaces
        
        :col: A Spark Column object containing text data
        :returns: A Spark Column object.

    """
    single_spaces = col.lower()
    single_spaces = re.sub("\s+", ' ', single_spaces)
    single_spaces = re.sub('[^a-z0-9 ]+', '', single_spaces) # Removes multiple white spaces
    
    single_spaces = single_spaces.rstrip()

    return single_spaces

def calculate_word_scores_toy(df_list, df_rev):
    """
        Calculates the word score over listings in df_list and
        reviews in df_rev. The table produced should have the 
        same columns as specified in part 1.
        
        :returns: A pandas DataFrame
    """

    clean = udf(lambda z :clean_text(z), StringType())
    data = df_rev.withColumn('comments',clean('comments'))
    
    data = data.withColumnRenamed('listing_id','id')
    
    df_join = data.join(df_list,on=['id'],how='inner')
    
    word_occurences = data.withColumn('word',F.explode(F.split(F.col('comments'), ' ')))\
        .where(F.length('word')>=4).distinct()\
        .groupBy('word','id')\
        .count()\
        .groupby('word')\
        .sum()\
        .withColumnRenamed('sum(count)','word_occurences')
    
    comment_occurences = data.withColumn('word',F.explode(F.split(F.col('comments'), ' ')))\
        .where(F.length('word')>=4).distinct()\
        .groupBy('word','id','comment_id')\
        .count()\
        .groupBy('word')\
        .count()\
        .withColumnRenamed('count','comment_occurences')
    
    listing_occurences = data.withColumn('word',F.explode(F.split(F.col('comments'), ' ')))\
        .where(F.length('word')>=4).distinct()\
        .groupBy('word','id')\
        .count()\
        .groupBy('word')\
        .count()\
        .withColumnRenamed('count','listing_occurences')
    
    word_score = df_join.select('comment_id','review_scores_rating',F.explode(F.split(F.col('comments'), ' ')).alias('word'))\
                        .where(F.length('word')>=4).distinct()\
                        .groupby('word')\
                        .agg(F.avg('review_scores_rating').alias('word_score'))
    
    for df in [listing_occurences,word_occurences,comment_occurences]:
        word_score=word_score.join(df,on=['word'],how='inner')

    return word_score

# %load_ext line_profiler
# %lprun -f calculate_word_scores_toy calculate_word_scores_toy(df_sentiment_listings_toy, df_sentiment_reviews_toy)
# load = %timeit -o -n1 -r1 display(calculate_word_scores_toy(df_sentiment_listings_toy, df_sentiment_reviews_toy))
# load.best

In [ ]:
ws=calculate_word_scores_toy(df_sentiment_listings_toy, df_sentiment_reviews_toy)

In [ ]:
ws.toPandas()

## Part 2: London comments (15 pts)

In this part we'll calculate word scores for the comments related to London listings only. You should implement `count_relevant_listings` and `calculate_word_scores` (it will be an extension of your function from part 1) below. See the mathematical definition and docstrings for intended behaviour.

The function `calculate_word_scores` should return the top 10 and bottom 10 words by score. You should **not** use caching in your function.

Make sure your satisfy all conditions for a word to be scored (e.g. correctly calculating how many total listings scores are computed over). You should also consider whether your query is optimally structured in terms of computation time. Moreover, `pd.set_option('display.max_rows', <n>)` should be set with sufficiently high `n` to show all words.

In [15]:
# your code goes here
def count_relevant_listings(df_list, df_rev):
    """
        Calculates the number of listings in df_list that has a 
        review in df_rev. A listing that is reviewed more than once
        should only count as one.
        
        :returns: An integer 

    """
    df_list=df_list.withColumnRenamed("id","listing_id")
    df_listings_reviews=df_list.join(df_rev, on=['listing_id'], how='left')
    num_listings=df_listings_reviews.groupby('listing_id').count()

    return num_listings.count()
    

def calculate_word_scores(df_list, df_rev, listings_count):
    """
        Calculates the word score over listings in df_list and
        reviews in df_rev. The value of listings_count should 
        be used to filter out words not occuring frequently enough
        in comments. The table produced should have the same columns
        as in part 1 of this exercise.
        
        :returns: A pandas DataFrame containing the top 10 and 
        bottom 10 words based on their word score, sorted by word_score.
    """
    
    clean = udf(lambda z :clean_text(z) if z is not None else z, StringType())
    data = df_rev.withColumn('comments',clean('comments'))
    
    data = data.withColumnRenamed('id','comment_id')
    data = data.withColumnRenamed('listing_id','id')
    
    df_list=df_list.withColumnRenamed('listing_id','id')
    
    df_join = data.join(df_list,on=['id'],how='inner')
    
    word_occurences = data.withColumn('word',F.explode(F.split(F.col('comments'), ' ')))\
        .where(F.length('word')>=4).distinct()\
        .groupBy('word','id')\
        .count()\
        .groupby('word')\
        .sum('count')\
        .withColumnRenamed('sum(count)','word_occurences')
    
    comment_occurences = data.withColumn('word',F.explode(F.split(F.col('comments'), ' ')))\
        .where(F.length('word')>=4).distinct()\
        .groupBy('word','id','comment_id')\
        .count()\
        .groupBy('word')\
        .count()\
        .withColumnRenamed('count','comment_occurences')
    
    listing_occurences = data.withColumn('word',F.explode(F.split(F.col('comments'), ' ')))\
        .where(F.length('word')>=4).distinct()\
        .groupBy('word','id')\
        .count()\
        .groupBy('word')\
        .count()\
        .withColumnRenamed('count','listing_occurences')
    
    word_score = df_join.select('comment_id','review_scores_rating',F.explode(F.split(F.col('comments'), ' ')).alias('word'))\
                        .where(F.length('word')>=4).distinct()\
                        .groupby('word')\
                        .agg(F.avg('review_scores_rating').alias('word_score'))
    
    for df in [listing_occurences,word_occurences,comment_occurences]:
        word_score=word_score.join(df,on=['word'],how='inner')
    
    word_score=word_score.filter(F.col('listing_occurences')/listings_count>0.005)
    
    word_score_top=word_score.sort('word_score',ascending=False).limit(10)
    word_score_bottom=word_score.sort('word_score',ascending=True).limit(10)
    word_score_bottom=word_score_bottom.sort('word_score',ascending=False)
    word_score=word_score_top.union(word_score_bottom)
    
    return word_score

In [ ]:
relevant_listings_count_london=count_relevant_listings(df_listings_london, df_reviews_london)

In [ ]:
ws=calculate_word_scores(df_listings_london, \
                          df_reviews_london, \
                          relevant_listings_count_london)

In [ ]:
ws.toPandas()

In [ ]:
# should not be modified
from IPython.display import display

relevant_listings_count_london = count_relevant_listings(df_listings_london, df_reviews_london)
word_scores_london_timing = %timeit -o -n1 -r1 display( \
    calculate_word_scores(df_listings_london, \
                          df_reviews_london, \
                          relevant_listings_count_london) \
)

word_scores_london_timing.best

## Part 3: Scalability (10 pts)

The listings from London make up a little less than 2% of the entire set of listings. In this part we're interested in how the amount of input data impacts computation time, that is, how `calculate_word_scores` scales as data increases. To this end, we've made multiple samples of the dataset of varying sizes.

The experiment reuses `count_relevant_listings` and `calculate_word_scores` that you implemented in part 2. Code needed for this part is provided to you. 

Your task is to obtain the data sources, run the code cells below, and explain the results you get. Specifically, you must explain any non-linear relationship between data size and computation time, using the markdown cell at the end of this part. In finding explanations, using the Spark UI to investigate the anatomy of your queries may prove valuable. Once you've found an explanation, state a potential solution to remedy the issue. Lastly, include a paragraph stating the specifications of your computer hardware (memory, CPU cores and clock speed, solid state disk or not) on which the experiment has been run.

*Implementation note* Make sure you've properly configured `spark.driver.memory` (it requires a kernel restart to update the value). It may be that your query fails on the larger samples due to running out of compute resources. This is likely caused by a suboptimal `calculate_word_scores`, but can be from reaching the limits of your hardware. If you think the latter is the case, argue for this perspective in the markdown cell.

Your data sources are (uncompress and place in the same directory as this notebook):
* 0.25%: [listings](https://data-download.compute.dtu.dk/c02807/listings_0-dot-25percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_0-dot-25percent.csv.zip)
* 0.5%: [listings](https://data-download.compute.dtu.dk/c02807/listings_0-dot-5percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_0-dot-5percent.csv.zip)
* 1%: [listings](https://data-download.compute.dtu.dk/c02807/listings_1-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_1-dot-0percent.csv.zip)
* 2%: [listings](https://data-download.compute.dtu.dk/c02807/listings_2-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_2-dot-0percent.csv.zip)
* 4%: [listings](https://data-download.compute.dtu.dk/c02807/listings_4-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_4-dot-0percent.csv.zip)
* 8%: [listings](https://data-download.compute.dtu.dk/c02807/listings_8-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_8-dot-0percent.csv.zip)
* 12.5%: [listings](https://data-download.compute.dtu.dk/c02807/listings_12-dot-5percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_12-dot-5percent.csv.zip)
* 16%: [listings](https://data-download.compute.dtu.dk/c02807/listings_16-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_16-dot-0percent.csv.zip)
* 25%: [listings](https://data-download.compute.dtu.dk/c02807/listings_25-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_25-dot-0percent.csv.zip)
* 50%: [listings](https://data-download.compute.dtu.dk/c02807/listings_50-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_50-dot-0percent.csv.zip)
* 75%: [listings](https://data-download.compute.dtu.dk/c02807/listings_75-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_75-dot-0percent.csv.zip)
* 100%: [listings](https://data-download.compute.dtu.dk/c02807/listings_100-dot-0percent.csv.zip), [reviews](https://data-download.compute.dtu.dk/c02807/reviews_100-dot-0percent.csv.zip)

In [16]:
import time
def calculate_word_scores_timed(percent_str):
    """
        Calculates word scores over a sampled dataset indicated
        by percent_str.
        
        :returns: A dictionary with benchmarking information and
        the calculated values.
    """
    df_listings = load_csv_as_dataframe(f'listings_{percent_str}percent.csv')
    df_reviews = load_csv_as_dataframe(f'reviews_{percent_str}percent.csv')
    
    listings_count = count_relevant_listings(df_listings, df_reviews)

    start = time.time()
    df_word_scores = calculate_word_scores(df_listings, df_reviews, listings_count)
    end = time.time()
    return {
        'percentage': float(percent_str.replace('-dot-', '.')), 
        'time_spent': f"{end - start:.2f}", 
        'relevant_listings': listings_count, 
        'df': df_word_scores
    }

In [17]:
data_percentages = [
    '0-dot-25', '0-dot-5', '1-dot-0', '2-dot-0', '4-dot-0', '8-dot-0','12-dot-5', '16-dot-0', '25-dot-0'
]
score_data = {
    percentage_str: calculate_word_scores_timed(percentage_str) for percentage_str in data_percentages
}

In [18]:
score_data['50-dot-0'] = calculate_word_scores_timed('50-dot-0')

In [19]:
score_data['75-dot-0'] = calculate_word_scores_timed('75-dot-0')

In [20]:
score_data['100-dot-0'] = calculate_word_scores_timed('100-dot-0')

In [21]:
df_scores_scaling = pd.DataFrame(score_data).T.convert_dtypes()
df_scores_scaling.time_spent = df_scores_scaling.time_spent.astype(float)

# Access to word scores of 2 percent data: df_scores_scaling.loc['2-dot-0'].df
df_scores_scaling

percentage  time_spent  relevant_listings  \
0-dot-25         0.25        0.40               3289   
0-dot-5           0.5        0.37               6568   
1-dot-0           1.0        0.38              13167   
2-dot-0           2.0        0.37              26729   
4-dot-0           4.0        0.27              53131   
8-dot-0           8.0        0.23             106261   
12-dot-5         12.5        0.23             166749   
16-dot-0         16.0        0.24             213090   
25-dot-0         25.0        0.25             333028   
50-dot-0         50.0        0.27             665317   
75-dot-0         75.0        0.26             998083   
100-dot-0       100.0        0.25            1330375   

                                                          df  
0-dot-25   DataFrame[word: string, word_score: double, li...  
0-dot-5    DataFrame[word: string, word_score: double, li...  
1-dot-0    DataFrame[word: string, word_score: double, li...  
2-dot-0    DataFrame[word: string, word_score: double, li...  
4-dot-0    DataFrame[word: string, word_score: double, li...  
8-dot-0    DataFrame[word: string, word_score: double, li...  
12-dot-5   DataFrame[word: string, word_score: double, li...  
16-dot-0   DataFrame[word: string, word_score: double, li...  
25-dot-0   DataFrame[word: string, word_score: double, li...  
50-dot-0   DataFrame[word: string, word_score: double, li...  
75-dot-0   DataFrame[word: string, word_score: double, li...  
100-dot-0  DataFrame[word: string, word_score: double, li...

In [ ]:
%matplotlib inline
fig, axes = plt.subplots(ncols=3, figsize=(15, 5))

lower_range = ['0-dot-25', '0-dot-5', '1-dot-0', '2-dot-0', '4-dot-0', '8-dot-0', '16-dot-0']
df_scores_scaling[df_scores_scaling.index.isin(lower_range)] \
    .plot.line(x='percentage', y='time_spent', ax=axes[0], style='-o', title='Lower range')
df_scores_scaling[~df_scores_scaling.index.isin(lower_range)] \
    .plot.line(x='percentage', y='time_spent', ax=axes[1], style='-o', title='Upper range')
_ = df_scores_scaling \
    .plot.line(x='percentage', y='time_spent', ax=axes[2], style='-o', title='All')

*Explain any non-linear relationship between data size and computation time.*

The data size and computation time have a non-linear relationship. In fact, there is no clear pattern between the data size and computation time. Observation shows that the data set with the longest computation time is the 1.0% data (0.3), while the 100.0% data set has the quickest computation time (0.21). The 8.0%, 12.5%, and 16.0% datasets have approximately the same computation times. In general, the computation times are quite similar to each other, which shows that our `calculate_word_scores` performs well despite the size of the data set.

*In finding explanations, using the Spark UI to investigate the anatomy of your queries may prove valuable.*

*Once you've found an explanation, state a potential solution to remedy the issue.*

The memory storage on this computer is 16GB, and while running the notebook, I needed to free up space in the memory in order to process all data. The computer has 6 CPU cores and 12 logical processors, with a clock speed of 2.1GHz. The experiment has been done with no use of an SSD. 

## Part 4: Robustness (5 pts)

In this part we'll explore robustness of our word scores, using the values we computed in part 3. We'll do so by comparing top/bottom words for three different samples of the dataset. Specifically, the scores from your maximum (e.g. 100%) computed sample are to be compared with the 12.5% and 2.0% scores.

Compute and display a dataframe that accounts for any word found in either of the three samples' top/bottom words, and additionally shows the related `word_score` and `word_occurences` values.

Note that `df_scores_scaling.loc['100-dot-0'].df` provides the word scores dataframe of the 100% sample (similarly for the other two). For this part you should rely on pandas functionality only.  Moreover, `pd.set_option('display.max_rows', <n>)` should be set with sufficiently high `n` to show all rows.

In [22]:
# your code goes here
words20=df_scores_scaling.loc['2-dot-0'].df
words125=df_scores_scaling.loc['12-dot-5'].df
words100=df_scores_scaling.loc['100-dot-0'].df

In [38]:
newDF=words20.union(words125)
newnewDF=newDF.union(words100)
newnewDF=newnewDF.groupby('word').count()

In [41]:
newnewDF=newnewDF.filter(F.col('count')==3)

# Exercise 4: Transactions analysis (55 pts)

In this exercise the goal is to analyse historical business transactions (sales of parts to other companies), and derive insights about both products and customers.

The company X produces and globally sells gadget parts to a number of other companies. You requested the sales department of X to provide you with access to the customer and sales transactions database. To your horror, you've found no such database exists, but the data is instead manually maintained in a spreadsheet (error-prone solution). Intrepid as you are, you've accepted to receive the spreadsheet data as a `.csv`, realizing already data cleaning will be necessary.

Your first step (parts 1 and 2) is to clean the data after which you will derive insights about X's business operations (parts 3 and 4).

The input data is available here: [transactions.csv](http://courses.compute.dtu.dk/02807/2021/projects/project2/transactions.csv)

**Using SQL**

In this final exercise you must write SQL to do the data processing in parts 3 and 4. This entails using `psql.sqldf` to execute your queries (up against `df_transactions_cleaned`) which will return a pandas dataframe. Each question should be answered with a *single* query. For visualisation the `psql.sqldf` call should be followed only by functions necessary to customize the plotting/layout steps or reshape the dataframe (i.e. no data processing take place after your SQL statement is materialized as a pandas dataframe).

In part 1 and 2 of this exercise, you should make use of pandas functionality.



## Part 1: Data cleaning (15 pts)

For each column in the dataframe, investigate and **correct** problematic aspects such as,
* Missing values: Insert meaningful values (data imputation). Detectable as `np.nan`'s. A typical value for imputation is the *mode* (most frequent value) of the distribution. If no proper data imputation is possible, you may resort to dropping rows.
* Incorrect values: Typos and other data mishaps are present as values are manually entered. Detectable as low-prevalence categorical values, or ambigious data links (e.g. company listed in multiple countries). If no proper value correction is possible, you may resort to dropping rows.

In both cases, your strategy for replacing values should be data-driven, that is, shaped by the patterns you observe in the data. It is allowed to skip correcting the data (and instead drop the rows) if few rows are improved by your corrections. If in doubt, do the correction.

After all your cleaning steps are completed, you should run the `PandasProfiler` on your cleaned dataset, which should now contain 0% missing cells. Lastly, summarize the issues you identified and how you addressed them.

### Read, profile and explain

As the first step, load the data naming the dataframe `df_transactions`, and make a copy named `df_transactions_cleaned` on which your data cleaning steps will be done. Establish an overview using `PandasProfiler` (but realize there's more to cleaning than what this tool will let you know). Write a paragraph on what the data is about (e.g. what does a row constitute), and a paragraph on what the profile report tells you.

In [ ]:
# your code goes here

*Your explanation here*

### Country column

In [ ]:
# your code goes here

### Company column

In [ ]:
# your code goes here

### City column

In [ ]:
# your code goes here

### Parts column

In [ ]:
# your code goes here

### Price column

In [ ]:
# your code goes here

### Date column

In [ ]:
#your code goes here

### Profile `df_transactions_cleaned` and summarize corrections made

In [ ]:
# your code goes here

*Your summary goes here*

## Part 2: Standardise prices (5 pts)

Transaction prices are recorded in the local currency of the client (EUR, GBP, USD or JPY). You will need to convert these prices from local currency into the common currency (chosen here as) EUR, for comparability. These standardised prices should be added as a column to the dataframe called `prices_euro`.

Consider a two step process where you 1) Identify what currency has been used, and 2) Calculate the price conversion. Step 1 may reveal the data is still not completely clean (so either correct by impute or drop). For Step 2 look up exchange rates on the Internet.

In [ ]:
# your code goes here

## Part 3: Business insights (15 pts)

### Company by revenue

The revenue of a company is its total value of orders, all time. Compute and visualise all companies by revenue in descending order.

In [ ]:
# your code goes here

### Country by revenue, per year

The revenue of a country in a time period, is its total value of orders in that time period. Compute and visualise all countries by revenue, for years 2016, 2017 and 2018. Your visualisation should have countries on the x-axis and multiple bars (one for each year).

In [ ]:
# your code goes here

### Orders per quarter, all companies

Compute and visualise the number of orders each company has placed in each quarter. Exclude quarters where the order count is less than 3. As always, be mindful to not produce a cluttered visualisation.

Part of your query should form a variable that converts `date` into `YEAR_QUARTER` format. Dealing with dates is via `STRFTIME` [docs](https://www.sqlite.org/lang_datefunc.html) which doesn't allow quarter extraction. Instead, it allows for extraction of month, which you can case on in order to produce the quarter (Q1, Q2, Q3, Q4).  

In [ ]:
# your code goes here

## Part 4: Parts and prices (20 pts)

### Parts demand changes

A different amount of orders are placed on parts each year. The demand of a part is the number of orders placed on it. The demand change of a part is the absolute difference between its average demand in 2016/2017, and its demand in 2018.

Compute and visualise the 15 parts whose demand change has been the largest.

In [ ]:
# your code goes here

### Popular parts pricing

The most popular parts are those whose demand has increased the most from its 2016/2017 average to 2018. We're interested to find out if popularity is due to a price drop, and also inform us if prices of these parts are properly adjusted.

The demand increase of a part is its 2018 demand minus its 2016/2017 average demand. The price change of a part is its average 2018 price minus its average 2016/2017 price.

Compute the parts whose demand has increased (has positive demand increase) and the change in price for each of these parts. Then visualise this relationship and include in the figure title the correlation (compute via pandas) between these two variables. Conclude which is most likely 1) Parts became more popular from a drop in prices, or 2) The sales department deserved its bonuses.

In [ ]:
# your code goes here

*your explanation goes here*